language: node_js
node_js:
  - "node"
env:
  - TEST_COUCHDB_ADDR=localhost:5984
  - TEST_ADMIN=test-admin
  - TEST_ADMIN_PASSWORD=test-admin-password
  - TEST_USER=test-user
  - TEST_USER_PASSWORD=test-user-password
  - ANOTHER_USER=another-user
  - ANOTHER_USER_PASSWORD=another-user-password

before_script:
  - curl -X PUT $TEST_COUCHDB_ADDR/_config/admins/$TEST_ADMIN -d "\"$TEST_ADMIN_PASSWORD\""
  - curl -X PUT $TEST_COUCHDB_ADDR/_users
  - curl -X PUT $TEST_COUCHDB_ADDR/_users/org.couchdb.user:$TEST_USER -d "{\"name\": \"$TEST_USER\", \"password\": \"$TEST_USER_PASSWORD\", \"roles\": [], \"type\": \"user\"}"
  - curl -X PUT $TEST_COUCHDB_ADDR/_users/org.couchdb.user:$ANOTHER_USER -d "{\"name\": \"$ANOTHER_USER\", \"password\": \"$ANOTHER_USER_PASSWORD\", \"roles\": [], \"type\": \"user\"}"

services:
  - couchdb
